env:
  browser: true
  es2021: true
  jest: true
extends:
  - airbnb
  - airbnb-typescript
  - plugin:react-hooks/recommended
  - plugin:@typescript-eslint/recommended
  - prettier
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  project: 'tsconfig.json'
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react-hooks
  - '@typescript-eslint'
  - prettier
settings:
  import/resolver:
    typescript: {}
rules:
  react/react-in-jsx-scope: off
  camelcase: error
  spaced-comment: error
  quotes: [ error, single ]
  no-duplicate-imports: error
